version: "3"

services:
    app:
        container_name: wallet_app
        build: .
        command: php -S 0.0.0.0:9000 -t /var/www/html/public/
        ports:
            - "9000:9000"
        volumes: 
            - .:/var/www/html/
            - /var/www/html/vendor/
        networks: 
            - server    

    db:
        image: mysql
        container_name: wallet_mysql
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_USER: admin      
            MYSQL_PASSWORD: admin   
            MYSQL_DATABASE: wallet
        ports: 
            - "3306:3306"
        networks: 
            - server 

networks: 
    server:
        driver: bridge 